# Generated by Django 4.1.3 on 2023-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='datacenter',
            field=models.CharField(max_length=20, verbose_name='Data Center'),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=20, verbose_name='World Name'),
        ),
        migrations.AlterField(
            model_name='world',
            name='server',
            field=models.CharField(max_length=20, verbose_name='Server'),
        ),
    ]
