# Generated by Django 4.1.3 on 2023-12-19 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_world_datacenter_alter_world_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
