# Generated by Django 4.1.3 on 2023-12-27 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Job Name")),
                (
                    "baseClass",
                    models.CharField(max_length=20, verbose_name="Base Class"),
                ),
                ("role", models.CharField(max_length=20, verbose_name="Role")),
            ],
            options={
                "verbose_name_plural": "Battle Jobs",
            },
        ),
    ]
